// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// tl_tlul_1to2 package generated by `tlgen.py` tool

package tl_tlul_1to2_pkg;

  localparam logic [31:0] ADDR_SPACE_D0 = 32'h 00000000;
  localparam logic [31:0] ADDR_SPACE_D1 = 32'h 20000000;

  localparam logic [31:0] ADDR_MASK_D0 = 32'h 1fffffff;
  localparam logic [31:0] ADDR_MASK_D1 = 32'h 1fffffff;

  localparam int N_HOST   = 1;
  localparam int N_DEVICE = 2;

  typedef enum int {
    TlD0 = 0,
    TlD1 = 1
  } tl_device_e;

  typedef enum int {
    TlH0 = 0
  } tl_host_e;

endpackage
