// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// tb__xbar_connect generated by `tlgen.py` tool

xbar_tlul_1to2 dut();

`DRIVE_CLK(clk_i)

initial force dut.clk_i = clk_i;

// TODO, all resets tie together
initial force dut.rst_ni = rst_n;

// Host TileLink interface connections
`CONNECT_TL_HOST_IF(h0, dut, clk_i, rst_n)

// Device TileLink interface connections
`CONNECT_TL_DEVICE_IF(d0, dut, clk_i, rst_n)
`CONNECT_TL_DEVICE_IF(d1, dut, clk_i, rst_n)
