// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_env_pkg__params generated by `tlgen.py` tool


// List of Xbar device memory map
tl_device_t xbar_devices[$] = '{
    '{"d0", '{
        '{32'h00000000, 32'h1fffffff}
    }},
    '{"d1", '{
        '{32'h20000000, 32'h3fffffff}
}}};

  // List of Xbar hosts
tl_host_t xbar_hosts[$] = '{
    '{"h0", 0, '{
        "d0",
        "d1"}}
};
