// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_tlul_1to2_bind module generated by `tlgen.py` tool for assertions
module xbar_tlul_1to2_bind;
`ifndef GATE_LEVEL
  // Host interfaces
  bind xbar_tlul_1to2 tlul_assert #(.EndpointType("Device")) tlul_assert_host_h0 (
    .clk_i  (clk_i),
    .rst_ni (rst_ni),
    .h2d    (tl_h0_i),
    .d2h    (tl_h0_o)
  );

  // Device interfaces
  bind xbar_tlul_1to2 tlul_assert #(.EndpointType("Host")) tlul_assert_device_d0 (
    .clk_i  (clk_i),
    .rst_ni (rst_ni),
    .h2d    (tl_d0_o),
    .d2h    (tl_d0_i)
  );
  bind xbar_tlul_1to2 tlul_assert #(.EndpointType("Host")) tlul_assert_device_d1 (
    .clk_i  (clk_i),
    .rst_ni (rst_ni),
    .h2d    (tl_d1_o),
    .d2h    (tl_d1_i)
  );
`endif
endmodule
