// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtb_tlul_sram_if_macro.h for the primary calling header

#ifndef VERILATED_VTB_TLUL_SRAM_IF_MACRO___024ROOT_H_
#define VERILATED_VTB_TLUL_SRAM_IF_MACRO___024ROOT_H_  // guard

#include "verilated.h"
#include "verilated_timing.h"
class Vtb_tlul_sram_if_macro___024unit;


class Vtb_tlul_sram_if_macro__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtb_tlul_sram_if_macro___024root final {
  public:
    // CELLS
    Vtb_tlul_sram_if_macro___024unit* __PVT____024unit;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__clk;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__rst_n;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__rerr;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__req;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__we;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__rvalid;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__rvalid_q;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_adapt__DOT__error_det;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_adapt__DOT__instr_error;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_adapt__DOT__intg_error_q;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_adapt__DOT__d_valid;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_adapt__DOT__missed_err_gnt_q;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_adapt__DOT____VdfgRegularize_h506ee29d_0_0;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_adapt__DOT__u_err__DOT__instr_wr_err;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_adapt__DOT__u_err__DOT__addr_sz_chk;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_adapt__DOT__u_err__DOT__mask_chk;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_adapt__DOT__u_err__DOT__fulldata_chk;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_adapt__DOT__u_reqfifo__DOT__wvalid_i;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_adapt__DOT__u_reqfifo__DOT__rready_i;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_adapt__DOT__u_reqfifo__DOT__gen_singleton_fifo__DOT__full_d;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_adapt__DOT__u_reqfifo__DOT__gen_singleton_fifo__DOT__full_q;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_adapt__DOT__u_sramreqfifo__DOT__wvalid_i;
        CData/*4:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_adapt__DOT__u_sramreqfifo__DOT__rdata_o;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_adapt__DOT__u_sramreqfifo__DOT__gen_singleton_fifo__DOT__full_d;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_adapt__DOT__u_sramreqfifo__DOT__gen_singleton_fifo__DOT__full_q;
        CData/*4:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_adapt__DOT__u_sramreqfifo__DOT__gen_singleton_fifo__DOT__storage;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_adapt__DOT__u_rspfifo__DOT__wvalid_i;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_adapt__DOT__u_rspfifo__DOT__rvalid_o;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_adapt__DOT__u_rspfifo__DOT__gen_singleton_fifo__DOT__full_q;
        CData/*7:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__0__KET____DOT__u_macro__DOT__qo_reg;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__0__KET____DOT__u_macro__DOT__cen_flag;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__0__KET____DOT__u_macro__DOT__write_flag;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__0__KET____DOT__u_macro__DOT__read_flag;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__0__KET____DOT__u_macro__DOT__ntf_Tcyc;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__0__KET____DOT__u_macro__DOT__ntf_Tckh;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__0__KET____DOT__u_macro__DOT__ntf_Tckl;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__0__KET____DOT__u_macro__DOT__ntf_tcs;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__0__KET____DOT__u_macro__DOT__ntf_tas;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__0__KET____DOT__u_macro__DOT__ntf_tds;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__0__KET____DOT__u_macro__DOT__ntf_tws;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__0__KET____DOT__u_macro__DOT__ntf_twis;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__0__KET____DOT__u_macro__DOT__ntf_tch;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__0__KET____DOT__u_macro__DOT__ntf_tah;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__0__KET____DOT__u_macro__DOT__ntf_tdh;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__0__KET____DOT__u_macro__DOT__ntf_twh;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__0__KET____DOT__u_macro__DOT__ntf_twih;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__0__KET____DOT__u_macro__DOT__no_st_viol;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__0__KET____DOT__u_macro__DOT__no_hd_viol;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__0__KET____DOT__u_macro__DOT__no_ck_viol;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__0__KET____DOT__u_macro__DOT__clk_dly;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__0__KET____DOT__u_macro__DOT__write_flag_dly;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__0__KET____DOT__u_macro__DOT__read_flag_dly;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__0__KET____DOT__u_macro__DOT__cen_dly;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__0__KET____DOT__u_macro__DOT__cen_fell;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__0__KET____DOT__u_macro__DOT__cen_not_rst;
        CData/*7:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__0__KET____DOT__u_macro__DOT__cd5;
        CData/*7:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__0__KET____DOT__u_macro__DOT__cdx;
        CData/*7:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__0__KET____DOT__u_macro__DOT__marked_a;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__0__KET____DOT__u_macro__DOT__cen_flag_dly;
        CData/*7:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__1__KET____DOT__u_macro__DOT__qo_reg;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__1__KET____DOT__u_macro__DOT__cen_flag;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__1__KET____DOT__u_macro__DOT__write_flag;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__1__KET____DOT__u_macro__DOT__read_flag;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__1__KET____DOT__u_macro__DOT__ntf_Tcyc;
    };
    struct {
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__1__KET____DOT__u_macro__DOT__ntf_Tckh;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__1__KET____DOT__u_macro__DOT__ntf_Tckl;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__1__KET____DOT__u_macro__DOT__ntf_tcs;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__1__KET____DOT__u_macro__DOT__ntf_tas;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__1__KET____DOT__u_macro__DOT__ntf_tds;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__1__KET____DOT__u_macro__DOT__ntf_tws;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__1__KET____DOT__u_macro__DOT__ntf_twis;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__1__KET____DOT__u_macro__DOT__ntf_tch;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__1__KET____DOT__u_macro__DOT__ntf_tah;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__1__KET____DOT__u_macro__DOT__ntf_tdh;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__1__KET____DOT__u_macro__DOT__ntf_twh;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__1__KET____DOT__u_macro__DOT__ntf_twih;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__1__KET____DOT__u_macro__DOT__no_st_viol;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__1__KET____DOT__u_macro__DOT__no_hd_viol;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__1__KET____DOT__u_macro__DOT__no_ck_viol;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__1__KET____DOT__u_macro__DOT__clk_dly;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__1__KET____DOT__u_macro__DOT__write_flag_dly;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__1__KET____DOT__u_macro__DOT__read_flag_dly;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__1__KET____DOT__u_macro__DOT__cen_dly;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__1__KET____DOT__u_macro__DOT__cen_fell;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__1__KET____DOT__u_macro__DOT__cen_not_rst;
        CData/*7:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__1__KET____DOT__u_macro__DOT__cd5;
        CData/*7:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__1__KET____DOT__u_macro__DOT__cdx;
        CData/*7:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__1__KET____DOT__u_macro__DOT__marked_a;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__1__KET____DOT__u_macro__DOT__cen_flag_dly;
        CData/*7:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__2__KET____DOT__u_macro__DOT__qo_reg;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__2__KET____DOT__u_macro__DOT__cen_flag;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__2__KET____DOT__u_macro__DOT__write_flag;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__2__KET____DOT__u_macro__DOT__read_flag;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__2__KET____DOT__u_macro__DOT__ntf_Tcyc;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__2__KET____DOT__u_macro__DOT__ntf_Tckh;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__2__KET____DOT__u_macro__DOT__ntf_Tckl;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__2__KET____DOT__u_macro__DOT__ntf_tcs;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__2__KET____DOT__u_macro__DOT__ntf_tas;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__2__KET____DOT__u_macro__DOT__ntf_tds;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__2__KET____DOT__u_macro__DOT__ntf_tws;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__2__KET____DOT__u_macro__DOT__ntf_twis;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__2__KET____DOT__u_macro__DOT__ntf_tch;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__2__KET____DOT__u_macro__DOT__ntf_tah;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__2__KET____DOT__u_macro__DOT__ntf_tdh;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__2__KET____DOT__u_macro__DOT__ntf_twh;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__2__KET____DOT__u_macro__DOT__ntf_twih;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__2__KET____DOT__u_macro__DOT__no_st_viol;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__2__KET____DOT__u_macro__DOT__no_hd_viol;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__2__KET____DOT__u_macro__DOT__no_ck_viol;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__2__KET____DOT__u_macro__DOT__clk_dly;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__2__KET____DOT__u_macro__DOT__write_flag_dly;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__2__KET____DOT__u_macro__DOT__read_flag_dly;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__2__KET____DOT__u_macro__DOT__cen_dly;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__2__KET____DOT__u_macro__DOT__cen_fell;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__2__KET____DOT__u_macro__DOT__cen_not_rst;
        CData/*7:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__2__KET____DOT__u_macro__DOT__cd5;
        CData/*7:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__2__KET____DOT__u_macro__DOT__cdx;
        CData/*7:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__2__KET____DOT__u_macro__DOT__marked_a;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__2__KET____DOT__u_macro__DOT__cen_flag_dly;
        CData/*7:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__3__KET____DOT__u_macro__DOT__qo_reg;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__3__KET____DOT__u_macro__DOT__cen_flag;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__3__KET____DOT__u_macro__DOT__write_flag;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__3__KET____DOT__u_macro__DOT__read_flag;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__3__KET____DOT__u_macro__DOT__ntf_Tcyc;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__3__KET____DOT__u_macro__DOT__ntf_Tckh;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__3__KET____DOT__u_macro__DOT__ntf_Tckl;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__3__KET____DOT__u_macro__DOT__ntf_tcs;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__3__KET____DOT__u_macro__DOT__ntf_tas;
    };
    struct {
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__3__KET____DOT__u_macro__DOT__ntf_tds;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__3__KET____DOT__u_macro__DOT__ntf_tws;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__3__KET____DOT__u_macro__DOT__ntf_twis;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__3__KET____DOT__u_macro__DOT__ntf_tch;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__3__KET____DOT__u_macro__DOT__ntf_tah;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__3__KET____DOT__u_macro__DOT__ntf_tdh;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__3__KET____DOT__u_macro__DOT__ntf_twh;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__3__KET____DOT__u_macro__DOT__ntf_twih;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__3__KET____DOT__u_macro__DOT__no_st_viol;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__3__KET____DOT__u_macro__DOT__no_hd_viol;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__3__KET____DOT__u_macro__DOT__no_ck_viol;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__3__KET____DOT__u_macro__DOT__clk_dly;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__3__KET____DOT__u_macro__DOT__write_flag_dly;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__3__KET____DOT__u_macro__DOT__read_flag_dly;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__3__KET____DOT__u_macro__DOT__cen_dly;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__3__KET____DOT__u_macro__DOT__cen_fell;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__3__KET____DOT__u_macro__DOT__cen_not_rst;
        CData/*7:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__3__KET____DOT__u_macro__DOT__cd5;
        CData/*7:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__3__KET____DOT__u_macro__DOT__cdx;
        CData/*7:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__3__KET____DOT__u_macro__DOT__marked_a;
        CData/*0:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__3__KET____DOT__u_macro__DOT__cen_flag_dly;
        CData/*0:0*/ __VdfgRegularize_he50b618e_0_0;
        CData/*0:0*/ __Vfunc_mubi4_test_invalid__5__Vfuncout;
        CData/*3:0*/ __Vfunc_mubi4_test_invalid__5__val;
        CData/*0:0*/ __Vfunc_mubi4_test_true_strict__6__Vfuncout;
        CData/*3:0*/ __Vfunc_mubi4_test_true_strict__6__val;
        CData/*0:0*/ __Vfunc_mubi4_test_true_strict__8__Vfuncout;
        CData/*3:0*/ __Vfunc_mubi4_test_true_strict__8__val;
        CData/*0:0*/ __Vfunc_mubi4_test_true_strict__9__Vfuncout;
        CData/*3:0*/ __Vfunc_mubi4_test_true_strict__9__val;
        CData/*0:0*/ __Vintraval_h57c051a3__0;
        CData/*0:0*/ __Vintraval_ha447b470__0;
        CData/*0:0*/ __Vintraval_h7ee04a24__0;
        CData/*0:0*/ __Vintraval_hc1e52bc4__0;
        CData/*0:0*/ __Vintraval_hccd7d94c__0;
        CData/*0:0*/ __Vintraval_h1f2c754a__0;
        CData/*0:0*/ __Vintraval_hd1b02d39__0;
        CData/*0:0*/ __Vintraval_h7e6bc218__0;
        CData/*0:0*/ __Vintraval_hef677ca9__0;
        CData/*0:0*/ __Vintraval_h0ec179f4__0;
        CData/*0:0*/ __Vintraval_hdf1a9ba7__0;
        CData/*0:0*/ __Vintraval_ha0148163__0;
        CData/*0:0*/ __Vintraval_hf20d2f19__0;
        CData/*0:0*/ __Vintraval_h78c23df8__0;
        CData/*0:0*/ __Vintraval_hc14dc0cd__0;
        CData/*0:0*/ __Vintraval_hcd5f43f9__0;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VstlPhaseResult;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP____VdfgRegularize_he50b618e_0_0__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__req__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__rvalid__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__we__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr_h81d9a602__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__0__KET____DOT__u_macro__DOT__cen_not_rst__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__0__KET____DOT__u_macro__DOT__cen_fell__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__0__KET____DOT__u_macro__DOT__clk_dly__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__1__KET____DOT__u_macro__DOT__cen_not_rst__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__1__KET____DOT__u_macro__DOT__cen_fell__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__1__KET____DOT__u_macro__DOT__clk_dly__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__2__KET____DOT__u_macro__DOT__cen_not_rst__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__2__KET____DOT__u_macro__DOT__cen_fell__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__2__KET____DOT__u_macro__DOT__clk_dly__0;
    };
    struct {
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__3__KET____DOT__u_macro__DOT__cen_not_rst__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__3__KET____DOT__u_macro__DOT__cen_fell__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__3__KET____DOT__u_macro__DOT__clk_dly__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__0__KET____DOT__u_macro__DOT__cen_flag__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__0__KET____DOT__u_macro__DOT__ntf_Tckh__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__0__KET____DOT__u_macro__DOT__ntf_Tckl__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__0__KET____DOT__u_macro__DOT__ntf_Tcyc__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__0__KET____DOT__u_macro__DOT__ntf_tah__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__0__KET____DOT__u_macro__DOT__ntf_tas__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__0__KET____DOT__u_macro__DOT__ntf_tch__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__0__KET____DOT__u_macro__DOT__ntf_tcs__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__0__KET____DOT__u_macro__DOT__ntf_tdh__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__0__KET____DOT__u_macro__DOT__ntf_tds__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__0__KET____DOT__u_macro__DOT__ntf_twh__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__0__KET____DOT__u_macro__DOT__ntf_twih__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__0__KET____DOT__u_macro__DOT__ntf_twis__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__0__KET____DOT__u_macro__DOT__ntf_tws__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__1__KET____DOT__u_macro__DOT__cen_flag__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__1__KET____DOT__u_macro__DOT__ntf_Tckh__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__1__KET____DOT__u_macro__DOT__ntf_Tckl__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__1__KET____DOT__u_macro__DOT__ntf_Tcyc__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__1__KET____DOT__u_macro__DOT__ntf_tah__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__1__KET____DOT__u_macro__DOT__ntf_tas__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__1__KET____DOT__u_macro__DOT__ntf_tch__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__1__KET____DOT__u_macro__DOT__ntf_tcs__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__1__KET____DOT__u_macro__DOT__ntf_tdh__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__1__KET____DOT__u_macro__DOT__ntf_tds__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__1__KET____DOT__u_macro__DOT__ntf_twh__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__1__KET____DOT__u_macro__DOT__ntf_twih__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__1__KET____DOT__u_macro__DOT__ntf_twis__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__1__KET____DOT__u_macro__DOT__ntf_tws__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__2__KET____DOT__u_macro__DOT__cen_flag__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__2__KET____DOT__u_macro__DOT__ntf_Tckh__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__2__KET____DOT__u_macro__DOT__ntf_Tckl__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__2__KET____DOT__u_macro__DOT__ntf_Tcyc__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__2__KET____DOT__u_macro__DOT__ntf_tah__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__2__KET____DOT__u_macro__DOT__ntf_tas__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__2__KET____DOT__u_macro__DOT__ntf_tch__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__2__KET____DOT__u_macro__DOT__ntf_tcs__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__2__KET____DOT__u_macro__DOT__ntf_tdh__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__2__KET____DOT__u_macro__DOT__ntf_tds__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__2__KET____DOT__u_macro__DOT__ntf_twh__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__2__KET____DOT__u_macro__DOT__ntf_twih__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__2__KET____DOT__u_macro__DOT__ntf_twis__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__2__KET____DOT__u_macro__DOT__ntf_tws__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__3__KET____DOT__u_macro__DOT__cen_flag__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__3__KET____DOT__u_macro__DOT__ntf_Tckh__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__3__KET____DOT__u_macro__DOT__ntf_Tckl__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__3__KET____DOT__u_macro__DOT__ntf_Tcyc__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__3__KET____DOT__u_macro__DOT__ntf_tah__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__3__KET____DOT__u_macro__DOT__ntf_tas__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__3__KET____DOT__u_macro__DOT__ntf_tch__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__3__KET____DOT__u_macro__DOT__ntf_tcs__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__3__KET____DOT__u_macro__DOT__ntf_tdh__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__3__KET____DOT__u_macro__DOT__ntf_tds__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__3__KET____DOT__u_macro__DOT__ntf_twh__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__3__KET____DOT__u_macro__DOT__ntf_twih__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__3__KET____DOT__u_macro__DOT__ntf_twis__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__3__KET____DOT__u_macro__DOT__ntf_tws__0;
        CData/*0:0*/ __VactPhaseResult;
        CData/*0:0*/ __VinactPhaseResult;
        CData/*0:0*/ __VnbaPhaseResult;
        SData/*15:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__addr;
        SData/*15:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_adapt__DOT__u_reqfifo__DOT__rdata_o;
    };
    struct {
        SData/*15:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_adapt__DOT__u_reqfifo__DOT__gen_singleton_fifo__DOT__storage;
        SData/*15:0*/ __VdfgRegularize_he50b618e_0_1;
        SData/*15:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__addr__0;
        IData/*31:0*/ tb_tlul_sram_if_macro__DOT__errors;
        IData/*31:0*/ tb_tlul_sram_if_macro__DOT__rd;
        IData/*31:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__wdata;
        IData/*31:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_adapt__DOT__wmask_o;
        IData/*31:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_adapt__DOT__error_blanking_data;
        IData/*31:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_adapt__DOT__rdata_tlword;
        IData/*31:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__0__KET____DOT__u_macro__DOT__i;
        IData/*31:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__1__KET____DOT__u_macro__DOT__i;
        IData/*31:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__2__KET____DOT__u_macro__DOT__i;
        IData/*31:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__3__KET____DOT__u_macro__DOT__i;
        IData/*31:0*/ __Vtrigprevexpr___TOP__tb_tlul_sram_if_macro__DOT__dut__DOT__wdata__0;
        IData/*31:0*/ __VactIterCount;
        IData/*31:0*/ __VinactIterCount;
        IData/*31:0*/ __Vi;
        VlWide<4>/*113:0*/ tb_tlul_sram_if_macro__DOT__tl_h2d;
        QData/*39:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_adapt__DOT__u_rspfifo__DOT__rdata_o;
        QData/*39:0*/ tb_tlul_sram_if_macro__DOT__dut__DOT__u_adapt__DOT__u_rspfifo__DOT__gen_singleton_fifo__DOT__storage;
        VlUnpacked<CData/*7:0*/, 256> tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__0__KET____DOT__u_macro__DOT__mem;
        VlUnpacked<CData/*7:0*/, 256> tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__1__KET____DOT__u_macro__DOT__mem;
        VlUnpacked<CData/*7:0*/, 256> tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__2__KET____DOT__u_macro__DOT__mem;
        VlUnpacked<CData/*7:0*/, 256> tb_tlul_sram_if_macro__DOT__dut__DOT__u_mem__DOT__gen_byte__BRA__3__KET____DOT__u_macro__DOT__mem;
        VlUnpacked<QData/*63:0*/, 1> __VstlTriggered;
        VlUnpacked<QData/*63:0*/, 2> __VactTriggered;
        VlUnpacked<QData/*63:0*/, 2> __VactTriggeredAcc;
        VlUnpacked<QData/*63:0*/, 2> __VnbaTriggered;
        VlUnpacked<CData/*0:0*/, 11> __Vm_traceActivity;
    };
    VlDelayScheduler __VdlySched;
    VlTriggerScheduler __VtrigSched_h608908bf__0;
    VlTriggerScheduler __VtrigSched_h4379b44b__0;
    VlTriggerScheduler __VtrigSched_h0726befb__0;
    VlTriggerScheduler __VtrigSched_h60890839__0;
    VlTriggerScheduler __VtrigSched_hcaabd044__0;
    VlTriggerScheduler __VtrigSched_h98ff2bfb__0;
    VlTriggerScheduler __VtrigSched_hc056ea11__0;
    VlTriggerScheduler __VtrigSched_h3b0f96f7__0;
    VlTriggerScheduler __VtrigSched_h6a0bc42b__0;
    VlTriggerScheduler __VtrigSched_h5a1955da__0;
    VlTriggerScheduler __VtrigSched_ha6669209__0;
    VlTriggerScheduler __VtrigSched_h385b2734__0;
    VlTriggerScheduler __VtrigSched_hd1994176__0;
    VlTriggerScheduler __VtrigSched_h1bc1ab8b__0;
    VlTriggerScheduler __VtrigSched_had15e284__0;

    // INTERNAL VARIABLES
    Vtb_tlul_sram_if_macro__Syms* vlSymsp;
    const char* vlNamep;

    // CONSTRUCTORS
    Vtb_tlul_sram_if_macro___024root(Vtb_tlul_sram_if_macro__Syms* symsp, const char* namep);
    ~Vtb_tlul_sram_if_macro___024root();
    VL_UNCOPYABLE(Vtb_tlul_sram_if_macro___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
