// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_tlul_2to4_bind module generated by `tlgen.py` tool for assertions
module xbar_tlul_2to4_bind;
`ifndef GATE_LEVEL
  // Host interfaces
  bind xbar_tlul_2to4 tlul_assert #(.EndpointType("Device")) tlul_assert_host_h_i (
    .clk_i  (clk_i),
    .rst_ni (rst_ni),
    .h2d    (tl_h_i_i),
    .d2h    (tl_h_i_o)
  );
  bind xbar_tlul_2to4 tlul_assert #(.EndpointType("Device")) tlul_assert_host_h_d (
    .clk_i  (clk_i),
    .rst_ni (rst_ni),
    .h2d    (tl_h_d_i),
    .d2h    (tl_h_d_o)
  );

  // Device interfaces
  bind xbar_tlul_2to4 tlul_assert #(.EndpointType("Host")) tlul_assert_device_d_rom (
    .clk_i  (clk_i),
    .rst_ni (rst_ni),
    .h2d    (tl_d_rom_o),
    .d2h    (tl_d_rom_i)
  );
  bind xbar_tlul_2to4 tlul_assert #(.EndpointType("Host")) tlul_assert_device_d_esram (
    .clk_i  (clk_i),
    .rst_ni (rst_ni),
    .h2d    (tl_d_esram_o),
    .d2h    (tl_d_esram_i)
  );
  bind xbar_tlul_2to4 tlul_assert #(.EndpointType("Host")) tlul_assert_device_d_dmem (
    .clk_i  (clk_i),
    .rst_ni (rst_ni),
    .h2d    (tl_d_dmem_o),
    .d2h    (tl_d_dmem_i)
  );
  bind xbar_tlul_2to4 tlul_assert #(.EndpointType("Host")) tlul_assert_device_d_uart (
    .clk_i  (clk_i),
    .rst_ni (rst_ni),
    .h2d    (tl_d_uart_o),
    .d2h    (tl_d_uart_i)
  );
`endif
endmodule
