// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_env_pkg__params generated by `tlgen.py` tool


// List of Xbar device memory map
tl_device_t xbar_devices[$] = '{
    '{"d_rom", '{
        '{32'h00000000, 32'h0000ffff}
    }},
    '{"d_esram", '{
        '{32'h00010000, 32'h0001ffff}
    }},
    '{"d_dmem", '{
        '{32'h00020000, 32'h0002ffff}
    }},
    '{"d_uart", '{
        '{32'h00030000, 32'h0003ffff}
}}};

  // List of Xbar hosts
tl_host_t xbar_hosts[$] = '{
    '{"h_i", 0, '{
        "d_rom",
        "d_esram"}}
    ,
    '{"h_d", 1, '{
        "d_esram",
        "d_dmem",
        "d_uart"}}
};
