// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_env_pkg__params generated by `tlgen.py` tool


// List of Xbar device memory map
tl_device_t xbar_devices[$] = '{
    '{"d_rom", '{
        '{32'h00000000, 32'h00000fff}
    }},
    '{"d_esram", '{
        '{32'h00001000, 32'h00001fff}
    }},
    '{"d_dmem", '{
        '{32'h00002000, 32'h00002fff}
    }},
    '{"d_uart", '{
        '{32'h00003000, 32'h00003fff}
}}};

  // List of Xbar hosts
tl_host_t xbar_hosts[$] = '{
    '{"h_i", 0, '{
        "d_rom",
        "d_esram"}}
    ,
    '{"h_d", 1, '{
        "d_esram",
        "d_dmem",
        "d_uart"}}
};
