#!/usr/bin/env bash
# setup.bash — one-time environment setup for the secure_boot_v0 example.
#
# Idempotent: safe to re-run. It does NOT need root unless it has to fall back
# to installing system packages (it never does that automatically — it only
# tells you the command to run).
#
# What it does:
#   1. Locates a RISC-V bare-metal GCC (riscv32- or riscv64-unknown-elf-).
#   2. Locates Verilator (>= 5) and OpenSSL.
#   3. Creates a Python venv and installs the FuseSoC version OpenTitan pins.
#   4. Initialises the micro-ecc git submodule used by the boot ROM.
#   5. Writes <example>/.env.local recording what it found; run_v0.bash reads it.
#
# Usage:
#   ./setup.bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$SCRIPT_DIR" && git rev-parse --show-toplevel)"
VENV="$REPO/.venv-fusesoc"
ENV_FILE="$SCRIPT_DIR/.env.local"
FUSESOC_VERSION="2.4.3"   # pinned by OpenTitan's python-requirements.txt

say()  { printf '\033[1;34m[setup]\033[0m %s\n' "$*"; }
ok()   { printf '\033[1;32m[ ok ]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[warn]\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31m[fail]\033[0m %s\n' "$*" >&2; exit 1; }

# ---------------------------------------------------------------------------
# 1) RISC-V toolchain
# ---------------------------------------------------------------------------
say "Locating a RISC-V bare-metal GCC ..."
RISCV_BIN=""
RISCV_PREFIX=""

# (a) Already on PATH?
for p in riscv32-unknown-elf- riscv64-unknown-elf-; do
  if command -v "${p}gcc" >/dev/null 2>&1; then
    RISCV_PREFIX="$p"
    RISCV_BIN="$(dirname "$(command -v "${p}gcc")")"
    break
  fi
done

# (b) Search common install locations.
if [[ -z "$RISCV_PREFIX" ]]; then
  for d in "$HOME/tools/riscv/bin" /opt/riscv/bin /opt/riscv32/bin /tools/riscv/bin; do
    for p in riscv32-unknown-elf- riscv64-unknown-elf-; do
      if [[ -x "$d/${p}gcc" ]]; then
        RISCV_PREFIX="$p"; RISCV_BIN="$d"; break 2
      fi
    done
  done
fi

if [[ -z "$RISCV_PREFIX" ]]; then
  die "No riscv32/64-unknown-elf-gcc found.
       Install a bare-metal RISC-V GCC (must build -march=rv32im -mabi=ilp32), e.g.:
         - prebuilt: https://github.com/riscv-collab/riscv-gnu-toolchain (newlib, multilib)
         - or unpack one under \$HOME/tools/riscv  (then re-run this script)
       Ubuntu's 'gcc-riscv64-unknown-elf' often lacks rv32 multilibs, so a prebuilt
       multilib toolchain is the safest bet."
fi
ok "RISC-V GCC: ${RISCV_BIN}/${RISCV_PREFIX}gcc  ($("${RISCV_BIN}/${RISCV_PREFIX}gcc" -dumpversion))"

# ---------------------------------------------------------------------------
# 2) Verilator + OpenSSL
# ---------------------------------------------------------------------------
if command -v verilator >/dev/null 2>&1; then
  VERILATOR_VER="$(verilator --version 2>/dev/null | awk '{print $2}')"
  ok "Verilator: $VERILATOR_VER"
  case "$VERILATOR_VER" in
    5.*|6.*) ;;
    *) warn "Verilator $VERILATOR_VER is older than 5.x — the OpenTitan IP may not build." ;;
  esac
else
  die "verilator not found. Install Verilator >= 5 (build from source or your package manager)."
fi

command -v openssl >/dev/null 2>&1 && ok "OpenSSL: $(openssl version)" \
  || die "openssl not found (needed to generate the image-signing key)."

# ---------------------------------------------------------------------------
# 3) FuseSoC venv
# ---------------------------------------------------------------------------
if [[ ! -d "$VENV" ]]; then
  say "Creating Python venv at $VENV ..."
  python3 -m venv "$VENV"
fi
# shellcheck disable=SC1091
source "$VENV/bin/activate"
say "Installing fusesoc==$FUSESOC_VERSION + packaging (quiet) ..."
pip install -q --upgrade pip >/dev/null
pip install -q "fusesoc==$FUSESOC_VERSION" packaging
ok "FuseSoC: $(fusesoc --version 2>&1)"
deactivate

# ---------------------------------------------------------------------------
# 4) micro-ecc submodule (used by the boot ROM signature path)
# ---------------------------------------------------------------------------
if [[ ! -f "$SCRIPT_DIR/sw/crypto/micro-ecc/uECC.c" ]]; then
  say "Initialising micro-ecc submodule ..."
  git -C "$REPO" submodule update --init playground/secure_boot_v0/sw/crypto/micro-ecc
fi
ok "micro-ecc present"

# ---------------------------------------------------------------------------
# 5) Record what we found
# ---------------------------------------------------------------------------
cat > "$ENV_FILE" <<EOF
# Generated by setup.bash — sourced by run_v0.bash. Safe to delete & regenerate.
export REPO="$REPO"
export FUSESOC_VENV="$VENV"
export RISCV_BIN="$RISCV_BIN"
export RISCV_PREFIX="$RISCV_PREFIX"
EOF
ok "Wrote $ENV_FILE"

echo
ok "Setup complete. Now run:  ./run_v0.bash"
