// rom_secure_boot_demo.c
//
// New file -- the "ROM" stage of a minimal 2-stage secure boot demo.
// Derives a private key from the PUF (same as puf_ecc_demo.c), computes
// its own public key from it, reads stage2's fixed 512-byte hash window
// directly out of IMEM over the data bus (the crossbar routes either host
// port to the "rom" device slot by address, so this works even though the
// bytes were originally written for instruction fetch), hashes it with
// SHA-256, and verifies the embedded signature (stage2_sig.h, generated by
// host_sign_stage2.c from the same known PUF bytes) against its own
// derived public key. Jumps to stage2 (a plain function-pointer call, not
// a CPU reset) only if verification succeeds.
//
// Deliberately out of scope for this demo (see conversation): PUF
// reliability/error-correction (assumes the same PUF bytes every run) and
// copy-from-storage (stage2 already lives in the same IMEM ROM reads from,
// no flash-to-RAM copy step).
#include <stdint.h>
#include "./utils/uart.h"
#include "./utils/micro-ecc/uECC.h"
#include "./utils/sha256.h"
#include "stage2_sig.h"

#define PUF_BASE 0x10000u

static inline uint32_t reg_read(uint32_t addr) { return *(volatile uint32_t *)addr; }
static inline void     reg_write(uint32_t addr, uint32_t val) { *(volatile uint32_t *)addr = val; }

static void uart_puts(const char *s) { while (*s) uart_putc(*s++); }

static void uart_put_hex8(uint8_t v) {
  static const char hexd[] = "0123456789ABCDEF";
  uart_putc(hexd[(v >> 4) & 0xF]);
  uart_putc(hexd[v & 0xF]);
}
static void uart_put_bytes(const uint8_t *buf, unsigned len) {
  for (unsigned i = 0; i < len; ++i) uart_put_hex8(buf[i]);
}

static uint32_t rng_state;
static uint32_t xorshift32(void) {
  uint32_t x = rng_state;
  x ^= x << 13; x ^= x >> 17; x ^= x << 5;
  rng_state = x;
  return x;
}
static int uecc_rng(uint8_t *dest, unsigned size) {
  for (unsigned i = 0; i < size; ++i) dest[i] = (uint8_t)(xorshift32() & 0xFF);
  return 1;
}

static void read_puf_key(uint8_t key[32]) {
  reg_write(PUF_BASE, 1);
  while (!(reg_read(PUF_BASE) & 1)) { }
  for (int w = 0; w < 8; w++) {
    uint32_t word = reg_read(PUF_BASE + 4u + 4u * (uint32_t)w);
    key[w * 4 + 0] = (uint8_t)(word >> 0);
    key[w * 4 + 1] = (uint8_t)(word >> 8);
    key[w * 4 + 2] = (uint8_t)(word >> 16);
    key[w * 4 + 3] = (uint8_t)(word >> 24);
  }
}

// Read stage2's hash window over the data bus (words, since the bus is
// word-granular) into a byte buffer.
static void read_stage2_window(uint8_t *out, uint32_t base, uint32_t len) {
  for (uint32_t i = 0; i < len; i += 4) {
    uint32_t word = reg_read(base + i);
    out[i + 0] = (uint8_t)(word >> 0);
    out[i + 1] = (uint8_t)(word >> 8);
    out[i + 2] = (uint8_t)(word >> 16);
    out[i + 3] = (uint8_t)(word >> 24);
  }
}

int main(void) {
  rng_state = 0x1u;

  uart_puts("ROM: deriving PUF key\r\n");

  uint8_t puf_key[32];
  read_puf_key(puf_key);

  uECC_set_rng(&uecc_rng);
  const struct uECC_Curve_t *curve = uECC_secp160r1();

  uint8_t private_key[21];
  uint8_t public_key[40];
  int found = 0;
  for (int i = 0; i < 21; i++) private_key[i] = 0;
  for (int i = 0; i < 20; i++) private_key[i + 1] = puf_key[i];
  for (int top = 0; top <= 1 && !found; top++) {
    private_key[0] = (uint8_t)top;
    if (uECC_compute_public_key(private_key, public_key, curve)) found = 1;
  }
  if (!found) {
    uart_puts("ROM FAIL: no valid PUF-derived private key\r\n");
    while (1) { }
  }
  uart_puts("ROM: public key ");
  uart_put_bytes(public_key, 40);
  uart_puts("\r\n");

  uint8_t window[STAGE2_HASH_LEN];
  read_stage2_window(window, STAGE2_ADDR, STAGE2_HASH_LEN);

  uint8_t hash[32];
  sha256_ctx_t sha;
  sha256_init(&sha);
  sha256_update(&sha, window, STAGE2_HASH_LEN);
  sha256_final(&sha, hash);
  uart_puts("ROM: stage2 hash ");
  uart_put_bytes(hash, 32);
  uart_puts("\r\n");

  int ok = uECC_verify(public_key, hash, sizeof(hash), stage2_signature, curve);
  if (!ok) {
    uart_puts("ROM: STAGE2 VERIFY FAIL\r\n");
    while (1) { }
  }
  uart_puts("ROM: stage2 verify OK, jumping\r\n");

  ((void (*)(void))STAGE2_ADDR)();

  // Should never return.
  uart_puts("ROM: stage2 returned unexpectedly\r\n");
  while (1) { }
  return 0;
}
