// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// tl_tlul_main package generated by `tlgen.py` tool

package tl_tlul_main_pkg;

  localparam logic [31:0] ADDR_SPACE_D_ROM   = 32'h 00000000;
  localparam logic [31:0] ADDR_SPACE_D_ESRAM = 32'h 00010000;
  localparam logic [31:0] ADDR_SPACE_D_DMEM  = 32'h 00020000;
  localparam logic [31:0] ADDR_SPACE_D_UART  = 32'h 00030000;
  localparam logic [31:0] ADDR_SPACE_D_HMAC  = 32'h 00040000;
  localparam logic [31:0] ADDR_SPACE_D_OTBN  = 32'h 00050000;

  localparam logic [31:0] ADDR_MASK_D_ROM   = 32'h 0000ffff;
  localparam logic [31:0] ADDR_MASK_D_ESRAM = 32'h 0000ffff;
  localparam logic [31:0] ADDR_MASK_D_DMEM  = 32'h 0000ffff;
  localparam logic [31:0] ADDR_MASK_D_UART  = 32'h 0000ffff;
  localparam logic [31:0] ADDR_MASK_D_HMAC  = 32'h 0000ffff;
  localparam logic [31:0] ADDR_MASK_D_OTBN  = 32'h 0000ffff;

  localparam int N_HOST   = 2;
  localparam int N_DEVICE = 6;

  typedef enum int {
    TlDRom = 0,
    TlDEsram = 1,
    TlDDmem = 2,
    TlDUart = 3,
    TlDHmac = 4,
    TlDOtbn = 5
  } tl_device_e;

  typedef enum int {
    TlHI = 0,
    TlHD = 1
  } tl_host_e;

endpackage
